#!/bin/bash
#SBATCH --partition mm_dev
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 4
#SBATCH --job-name test
#SBATCH --quotatype spot
#SBATCH --gres gpu:1
#SBATCH --output /mnt/petrelfs/huwenxing/.log/phoenix-slurm-%j.out
# args: --partition=mm_dev
# args: --ntasks=1
# args: --ntasks-per-node=1
# args: --cpus-per-task=4
# args: --kill-on-bad-exit=1
# args: --job-name=test
# args: --quotatype=spot
# args: --gres=gpu:1
# args: python
# args: tools/train.py
# args: configs/cfa/cfa-qbox_convnext-t_fpn_40e_dota.py
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
